import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppProvider from "./AppProvider";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get("sessionToken");
  console.log("cookieStore", sessionToken);
  return (
    <html lang="en">
      <body>
        <AppProvider initialSessionToken={sessionToken?.value}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
